version: '3.4'
services:
  service1:
    build: 
      context: ./Backend_Service_1_Final
    ports:
      - "8081:8081"
    environment:
      JAEGER_AGENT_HOST: jaeger
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health_check"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - jaeger
      - rabbitmq
    networks:
      - abnet      

  service2:
    build: 
      context: ./Backend_Service_2_Final
    ports:
      - "8082:8082"
    environment:
      JAEGER_AGENT_HOST: jaeger
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health_check"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - jaeger
      - rabbitmq
    networks:
      - abnet

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - abnet

  krakend:
    image: devopsfaith/krakend:2.1.3
    volumes:
      - ./Manage_services/Krakend:/etc/krakend
    ports:
      - "8080:8080"
    depends_on:
      - service1
      - service2
      - jaeger
    networks:
      - abnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/v1/healthcheck"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s     
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./Manage_services/Prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - service1
      - service2
    networks:
      - abnet      
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - ./Manage_services/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
      - ./Manage_services/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
    networks:
      - abnet      

  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - abnet

  zabbix:
    image: zabbix/zabbix-appliance:latest
    ports:
      - "80:80"
      - "10051:10051"
    networks:
      - abnet
    depends_on:
      - service1
      - service2

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - abnet

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8443:8080"
    restart: unless-stopped
    networks:
      - abnet    

volumes:
  grafana-data:
  elasticsearch_data:
    driver: local

networks:
  abnet:
    driver: bridge