global:
  scrape_interval: 15s
scrape_configs:
  - job_name: service1-metrics
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8081
  - job_name: service2-metrics
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8082